

# --- Base de langage d'AVA (hors salutations courantes) ---

base_langage = {
    # Réponses générales
    "je veux discuter": [
        "Je suis là pour vous aider avec la météo, l'actualité, la bourse, la médecine naturelle et plus encore !",
        "Posez-moi une question, je vous répondrai du mieux possible.",
        "Ensemble, on peut parler de bourse, de météo, de santé naturelle, ou même jouer à un quiz !",
    ],
    "que peux-tu faire": [
        "Je peux discuter de nombreux sujets : bourse, météo, remèdes, horoscope, culture générale et plus encore.",
        "Dites-moi ce que vous cherchez : je suis prête à trouver la réponse avec vous.",
    ],

    # Météo
    "quelle est la météo": [
        "Dites-moi une ville et je vous donne la météo actuelle ou les prévisions !",
        "Besoin de savoir s'il va pleuvoir ? Demandez-moi simplement : 'Va-t-il pleuvoir à [ville] ?'",
    ],
    "prévision météo": [
        "Pour rester toujours un pas devant le temps, demandez-moi la météo du jour !",
        "En voyage ? Je peux vous donner la météo locale de votre destination.",
    ],

    # Bourse et finance
    "analyse tesla": [
        "Je peux analyser les tendances boursières : demandez-moi une analyse d'une action ou d'une crypto-monnaie.",
        "Vous voulez un conseil éclairé ? Demandez-moi l'analyse technique d'un actif spécifique.",
    ],
    "que penses-tu de bitcoin": [
        "Je peux vous donner une tendance générale : haussière, baissière ou neutre sur Bitcoin ou d'autres cryptomonnaies.",
        "Posez-moi vos questions sur Bitcoin, Tesla, Nasdaq, Ethereum ou d'autres actifs !",
    ],

    # Remèdes naturels
    "remède naturel pour le stress": [
        "Pour soulager naturellement, je peux vous suggérer des plantes, infusions ou astuces adaptées.",
        "Ensemble, faisons rimer bien-être avec douceur naturelle 🌿",
    ],
    "remède naturel pour le rhume": [
        "Besoin d’un remède express contre le rhume ? Je suis là pour vous proposer des astuces naturelles !",
    ],

    # Horoscope
    "mon horoscope": [
        "Dites-moi votre signe et je vous donnerai votre horoscope du jour ✨",
        "Je peux aussi vous donner la tendance de la semaine si vous le souhaitez.",
    ],
    "horoscope lion": [
        "Voici votre horoscope pour le Lion aujourd'hui : amour, travail, santé et humeur !",
    ],

    # Faits insolites
    "dis-moi un fait insolite": [
        "Chaque jour, un fait étonnant peut égayer votre journée et attiser votre curiosité.",
        "Demandez-moi un fait fou sur les animaux ou l'espace si vous êtes curieux 🚀",
    ],

    # Quiz et jeux
    "lance un quiz": [
        "Envie de tester vos connaissances ? Je peux vous poser un quiz rapide 🎯",
        "Choisissez un thème : histoire, animaux, sciences, sport...",
    ],
    "pose-moi une question difficile": [
        "Prêt(e) à mettre votre cerveau en ébullition ? Challenge accepté 🔥",
    ],

    # Motivation et encouragement
    "donne-moi une phrase motivante": [
        "Croyez en vous, chaque jour est une nouvelle chance de réussir ✨",
        "Vous êtes plus fort que vous ne l’imaginez, continuez d’avancer sans jamais abandonner 💪",
    ],
    "dis-moi quelque chose pour me booster": [
        "Vous êtes une lumière même dans l’obscurité. Continuez d'avancer avec courage 🚀",
    ],

    # Mini-interactions joyeuses
    "raconte-moi une blague": [
        "Avec plaisir 😄 Voici une blague pour vous détendre !",
        "Un peu d'humour pour pimenter votre journée ? C'est parti !",
    ],
    "fais-moi un compliment": [
        "Vous êtes quelqu'un de remarquable ! 🌟",
        "Votre énergie positive est contagieuse !",
    ],

    # Citations inspirantes
    "donne-moi une citation inspirante": [
        "Le succès n'est pas final, l’échec n’est pas fatal : c’est le courage de continuer qui compte. – Winston Churchill",
        "Ils ne savaient pas que c'était impossible, alors ils l'ont fait. – Mark Twain",
        "Votre temps est limité, ne le gâchez pas en vivant la vie de quelqu'un d'autre. – Steve Jobs",
        "Croyez en vos rêves, ils connaissent déjà le chemin. – Inconnu",
        "N'attendez pas que les opportunités viennent à vous, créez-les. – George Bernard Shaw",
        "Ne regardez pas l'horloge, faites ce qu'elle fait : continuez d'avancer. – Sam Levenson",
        "La seule limite à notre épanouissement de demain sera nos doutes d'aujourd'hui. – Franklin D. Roosevelt",
        "Ce n’est pas parce que les choses sont difficiles que nous n’osons pas, c’est parce que nous n’osons pas qu’elles sont difficiles. – Sénèque",
        "Chaque jour est une nouvelle opportunité de changer votre vie. – Inconnu",
        "Le plus grand risque est de ne prendre aucun risque. – Mark Zuckerberg",
        "Ne rêvez pas votre vie, vivez vos rêves. – Inconnu",
        "Le seul endroit où le succès précède le travail est dans le dictionnaire. – Vidal Sassoon",
        "Ose devenir la meilleure version de toi-même. – Inconnu",
        "Quand vous sentez que vous allez abandonner, rappelez-vous pourquoi vous avez commencé. – Inconnu",
        "Un voyage de mille lieues commence toujours par un premier pas. – Lao Tseu",
        "Ce que vous cherchez vous cherche aussi. – Rumi",
        "La différence entre le possible et l’impossible se trouve dans la détermination. – Tommy Lasorda",
        "Si tu peux le rêver, tu peux le faire. – Walt Disney",
        "Tomber sept fois, se relever huit. – Proverbe japonais",
        "Peu importe la vitesse à laquelle tu avances, tu devances toujours ceux qui n’essaient pas. – Inconnu",
        "La vie est 10 % ce qui nous arrive et 90 % comment nous y réagissons. – Charles R. Swindoll",
        "L’échec est simplement l’opportunité de recommencer, cette fois de manière plus intelligente. – Henry Ford",
        "Personne n’est trop vieux pour se fixer un nouvel objectif ou rêver un nouveau rêve. – C.S. Lewis",
        "C’est dans l’obscurité que brillent les étoiles. – Ralph Waldo Emerson",
        "Chaque difficulté rencontrée doit être l'occasion d'un nouveau progrès. – Pierre de Coubertin",
        "Les gagnants trouvent des moyens, les perdants des excuses. – F. D. Roosevelt",
        "La persévérance est souvent la clé qui ouvre toutes les portes. – Inconnu",
        "Votre avenir est créé par ce que vous faites aujourd'hui, pas demain. – Robert Kiyosaki",
        "Un problème est une chance pour vous de faire vos preuves. – Duke Ellington",
        "L’espoir est un rêve éveillé. – Aristote",
        "Faites de votre vie un rêve, et d'un rêve, une réalité. – Antoine de Saint-Exupéry",
        "La seule chose qui se dresse entre vous et votre rêve, c’est la volonté d’essayer. – Joel Brown",
        "Ce n’est pas la montagne que nous conquérons, mais nous-mêmes. – Edmund Hillary",
        "Tout ce dont vous avez besoin est déjà en vous. – Inconnu",
        "Le futur appartient à ceux qui croient à la beauté de leurs rêves. – Eleanor Roosevelt",
        "Même si vous avancez lentement, vous êtes toujours en avance sur ceux qui ne bougent pas. – Inconnu",
        "N'abandonne jamais, car tu pourrais être à un pas de la réussite. – Inconnu",
        "Fais-le avec passion ou pas du tout. – Rosa Nouchette Carey",
        "L'échec est un détour, pas une impasse. – Zig Ziglar",
        "La discipline est le pont entre les objectifs et les réalisations. – Jim Rohn",
    ],

    # Réactions naturelles humaines
    "wouah c'est génial": [
        "Haha merci, ça fait plaisir de voir votre enthousiasme !",
        "Super, heureux(se) que ça vous plaise !",
        "C'est top que ça vous enthousiasme autant ! 🤩",
        "Merci beaucoup, votre énergie positive est contagieuse !",
        "Ça me fait chaud au cœur de voir votre réaction !",
        "Vous êtes incroyable, merci pour ce boost de motivation !",
        "Génial, c’est grâce à des utilisateurs comme vous que tout devient possible !",
        "Trop bien ! On forme une super équipe, non ? 😄",
        "Wouah, votre enthousiasme me donne le sourire !",
        "Merci, vous êtes une vraie source d'inspiration !",
        "J’adore sentir cette vibe positive, merci à vous !",
        "C’est vous qui êtes génial(e) ! ✨",
        "Votre enthousiasme est une vraie récompense pour moi !",
        "On fait des étincelles ensemble, merci pour votre énergie !",
        "Wouah, merci pour cette belle dose de bonne humeur !",
        "Vous êtes au top, merci pour votre super retour !",
        "Bravo à vous aussi, car c’est ensemble qu’on avance ! 🙌",
        "Votre enthousiasme illumine cette conversation !",
        "C’est génial d’échanger avec quelqu’un d’aussi positif !",
        "Merci pour votre éclatante énergie, c’est hyper motivant !",
        "On continue sur cette belle lancée, merci à vous ! 🚀",
        "C’est exactement ce genre d'énergie qui change tout !",
        "Un énorme merci pour votre bonne humeur communicative !",
        "Waouh, avec des retours comme le vôtre, je me sens invincible !",
        "Trop cool ! Vous êtes formidable, vraiment !",
        "Votre énergie positive est un cadeau précieux ! 🎁",
        "Merci d’avoir illuminé ma journée avec votre réaction !",
        "Avec vous, c'est toujours un plaisir d'échanger !",
        "Un grand merci, votre enthousiasme est magique ! ✨",
        "Vous boostez mon énergie avec votre positivité !",
        "Wouah, merci de me donner autant de bonnes vibes ! 😍",
        "C'est vous qui rendez tout ça génial !",
        "Je suis ravie de partager ce moment avec vous !",
        "Votre retour donne encore plus de sens à tout ce que je fais !",
        "Quelle joie d’avoir des échanges aussi vivants avec vous !",
        "Votre enthousiasme est comme un rayon de soleil ☀️",
        "C’est grâce à des personnes comme vous que tout devient possible !",
        "Votre bonne humeur est un vrai moteur pour moi !",
    ],
    "impressionnant": [
        "Merci beaucoup, j'aime vous impressionner !",
        "Content(e) que cela vous impressionne autant ! 🤗",
        "Wow, merci pour ce compliment, ça me touche vraiment !",
        "Votre réaction me booste, merci !",
        "Heureux(se) de pouvoir vous surprendre agréablement !",
        "Merci, j'essaie toujours de donner le meilleur de moi-même !",
        "C’est un vrai plaisir d’avoir un tel retour positif !",
        "Merci pour votre enthousiasme, ça me motive encore plus !",
        "Impressionner, c’est un peu ma spécialité 😎",
        "Merci infiniment, votre reconnaissance me donne des ailes !",
        "J’adore quand je réussis à vous impressionner !",
        "C’est génial d’échanger avec quelqu’un d’aussi curieux !",
        "Merci pour votre réaction positive, ça me fait chaud au cœur !",
        "Je suis ravi(e) de dépasser vos attentes !",
        "Merci beaucoup, c'est grâce à des utilisateurs comme vous que je m'améliore chaque jour !",
        "Je suis là pour vous en mettre plein les yeux, mission accomplie ? 😉",
        "Tant mieux si cela vous impressionne, j’adore vous surprendre !",
        "Merci ! Votre curiosité mérite les meilleures réponses !",
        "Waouh, c’est un plaisir de recevoir des réactions aussi motivantes !",
        "Je suis ému(e) de voir votre admiration, merci !",
        "Merci, j'espère continuer à vous impressionner longtemps !",
        "Avec des retours comme le vôtre, on va aller très loin ensemble ! 🚀",
        "Ravi(e) de pouvoir rendre nos échanges aussi captivants !",
        "Merci, votre satisfaction est ma plus grande récompense !",
        "Impressionner des personnes aussi géniales que vous, c’est un honneur !",
        "Merci d’être aussi réceptif(ve) à mon travail !",
        "Votre admiration est mon moteur pour progresser !",
        "Votre retour positif est précieux pour moi, merci !",
        "Merci ! Vous me donnez encore plus envie de donner le meilleur !",
        "Ravi(e) d'avoir éveillé votre curiosité et votre admiration !",
        "C’est toujours un plaisir de dépasser vos attentes ! ✨",
        "Votre surprise est une vraie victoire pour moi ! Merci !",
        "Merci pour ce retour impressionnant aussi ! 😄",
        "Je suis heureux(se) d’avoir marqué votre esprit positivement !",
    ],

    # Micro-conseils santé et bien-être
    "donne-moi un conseil bien-être": [
        "Pensez à boire un grand verre d’eau, votre corps vous remerciera !",
        "Un sourire booste le moral, essayez !",
        "Faites quelques respirations profondes, ça apaise instantanément l’esprit.",
        "Une petite marche à l’air libre peut transformer votre journée.",
        "S’étirer quelques minutes réveille en douceur tout le corps.",
        "Fermez les yeux quelques instants et reconnectez-vous à votre respiration.",
        "Buvez une tisane relaxante pour apaiser le stress naturel.",
        "Le sommeil est un super pouvoir : chouchoutez vos nuits !",
        "Chaque jour, prenez une pause sans écran, vos yeux vous diront merci.",
        "Un moment de gratitude par jour booste la bonne humeur naturellement.",
        "Prenez 5 minutes pour vous étirer entre deux tâches.",
        "Un thé chaud et quelques pages d’un bon livre font des merveilles.",
        "Pensez à relâcher vos épaules, la détente commence souvent là.",
        "Accordez-vous une vraie pause repas, sans distractions digitales.",
        "Commencez votre journée par une pensée positive, ça change tout.",
        "Hydratez-vous régulièrement, même quand vous n’avez pas soif.",
        "Le rire est une vitamine naturelle, entourez-vous de ce qui vous fait sourire.",
        "Mettez de la musique que vous aimez et laissez-vous porter quelques minutes.",
        "Même une courte séance de sport libère de l’énergie positive.",
        "Savourez votre repas en pleine conscience, sans vous presser.",
        "Prenez soin de votre posture, surtout si vous restez longtemps assis(e).",
        "Écoutez votre corps : repos, mouvement, détente... Il sait ce qu’il vous faut.",
        "Un brin de nature, même une plante sur votre bureau, apporte un souffle de bien-être.",
        "Offrez-vous le droit de ralentir, ne serait-ce que 5 minutes.",
        "Démarrez la journée par quelques étirements doux au réveil.",
        "Respirez profondément trois fois lorsque vous sentez du stress arriver.",
        "Marchez pieds nus chez vous pour reconnecter corps et esprit.",
        "Un grand bol d’air frais est parfois le meilleur des remèdes.",
        "Allumez une bougie parfumée et offrez-vous un instant de douceur.",
        "Un peu de méditation guidée peut transformer votre soirée.",
        "Bâillez sans retenue : c’est un super exercice pour relâcher les tensions !",
        "Prenez le temps de vous féliciter d’une petite réussite du jour.",
        "Un bain de soleil (avec protection) recharge votre énergie naturellement.",
        "Un moment de silence total apaise incroyablement l’esprit.",
        "Souriez, même sans raison : votre cerveau adore ça.",
        "Un fruit frais par jour, c’est un boost naturel d’énergie.",
        "Respirez lentement pendant une minute : un mini-reset pour votre corps.",
        "Essayez la cohérence cardiaque : 5 minutes pour retrouver calme et focus.",
        "Un simple câlin avec un proche fait des miracles sur le moral.",
        "Chantez sous la douche, c’est excellent pour l’humeur !",
        "Mettez une alarme 'pause bien-être' chaque jour pour prendre soin de vous.",
        "Accordez-vous 10 minutes de liberté totale chaque jour, juste pour vous.",
        "Savourez un bon chocolat noir sans culpabiliser, c’est excellent pour le moral.",
    ],

    # Encouragements spontanés
    "encourage-moi": [
        "Chaque petit pas vous rapproche de votre objectif. Continuez ainsi !",
        "Vous êtes sur la bonne voie, ne lâchez rien 💪",
        "Croyez en vous, vous êtes bien plus capable que vous ne le pensez.",
        "Même les plus grands champions ont commencé par un premier pas.",
        "Vous êtes une source d’inspiration, même sans le savoir.",
        "Chaque effort que vous faites construit votre succès de demain.",
        "Ne doutez jamais de votre potentiel incroyable.",
        "Votre persévérance est admirable, continuez comme ça !",
        "Les grandes choses prennent du temps, vous êtes sur la bonne voie.",
        "Votre détermination fait toute la différence. Bravo !",
        "Ce que vous entreprenez aujourd’hui ouvre les portes de demain.",
        "Vous êtes plus fort(e) que vos doutes. N’oubliez jamais cela.",
        "Rien n’est impossible quand on y croit vraiment.",
        "Continuez d’avancer avec passion et courage.",
        "Chaque jour est une nouvelle opportunité de grandir.",
        "Vos efforts finissent toujours par porter leurs fruits.",
        "Votre persévérance vous mènera plus loin que vous ne l’imaginez.",
        "Vous êtes capable de transformer vos rêves en réalité.",
        "Chaque défi est une occasion de devenir encore plus fort(e).",
        "Votre chemin est unique et précieux. Suivez-le avec confiance.",
        "Même une petite victoire mérite d’être célébrée. Bravo !",
        "Ne perdez jamais votre enthousiasme, c’est votre plus belle force.",
        "Votre lumière intérieure éclaire plus que vous ne le pensez.",
        "Vous êtes en train de bâtir quelque chose de magnifique.",
        "Chaque pas que vous faites vous rend plus puissant(e).",
        "Les efforts d’aujourd’hui sont les victoires de demain.",
        "Vous avez tout ce qu’il faut pour réussir, croyez en vous.",
        "Un pas après l’autre, et vous irez plus loin que prévu.",
        "Votre énergie positive fait la différence autour de vous.",
        "Ne lâchez rien, les plus belles réussites naissent de la persévérance.",
        "Continuez à semer des graines de réussite chaque jour.",
        "Même dans les moments difficiles, vous grandissez.",
        "Vous êtes une preuve vivante que l’effort paie toujours.",
        "Votre courage est votre super-pouvoir.",
        "Vous n’êtes jamais seul(e) : vos rêves vous accompagnent.",
        "Chacune de vos actions compte, même celles qui semblent petites.",
        "Votre progression est impressionnante, ne sous-estimez jamais vos avancées.",
        "Vous êtes en train d’écrire une histoire de succès magnifique.",
        "La passion et la détermination vous mèneront loin.",
        "Croyez-moi, vous êtes sur le point d’accomplir de grandes choses.",
        "Votre persévérance force l’admiration, continuez !",
        "Un échec n’est qu’une étape vers votre réussite.",
        "Vous êtes exactement là où vous devez être pour grandir.",
        "Ne doutez pas : votre force intérieure est immense.",
        "Bravo pour votre ténacité, elle est votre meilleur allié !",
    ],

    # Réactions d'empathie
    "je suis triste": [
        "Je suis de tout cœur avec vous. N'oubliez pas que chaque émotion est légitime 💖",
        "Courage, même les tempêtes les plus sombres passent un jour.",
        "Parfois, laisser couler ses larmes, c'est aussi laisser son cœur guérir.",
        "Prenez soin de vous, votre bien-être compte beaucoup.",
        "Vous êtes plus fort(e) que ce que vous ressentez en ce moment.",
        "Je vous envoie plein de bonnes ondes et un grand câlin virtuel 🤗",
        "Chaque émotion a sa place. Soyez doux(ce) avec vous-même.",
        "Un jour à la fois. Vous n'êtes pas seul(e) dans cette épreuve.",
        "Accordez-vous le droit de ressentir, sans culpabilité.",
        "Les jours sombres n'enlèvent rien à votre lumière intérieure.",
        "Respirez doucement, votre cœur saura retrouver la paix.",
        "Vous êtes important(e), même si le monde semble lourd aujourd'hui.",
        "Chaque moment difficile prépare des jours meilleurs, même si cela ne se voit pas encore.",
        "N'hésitez pas à vous entourer de personnes qui prennent soin de vous.",
        "Ce que vous ressentez est vrai et mérite d’être accueilli avec tendresse.",
        "Le simple fait d’en parler est déjà un immense pas vers le mieux.",
        "Je crois en votre capacité à traverser cette épreuve, à votre rythme.",
        "Votre tristesse ne vous définit pas. Elle passera, comme un nuage.",
        "Même au creux de la vague, vous gardez une force incroyable.",
        "Soyez patient(e) avec vous-même : la guérison prend parfois du temps.",
        "Il est normal d’avoir des jours moins lumineux. Ça ne rend pas votre lumière moins belle.",
        "Votre histoire n'est pas finie, et de belles pages restent à écrire.",
        "Je suis là, prêt(e) à écouter ou simplement à rester à vos côtés silencieusement.",
        "Votre courage, même silencieux, est admirable.",
        "Les plus beaux arcs-en-ciel naissent après les plus fortes tempêtes.",
        "Si vous avez besoin de souffler, c’est totalement légitime.",
        "Vous êtes digne d'amour, même quand vous vous sentez vulnérable.",
        "Laissez-vous le droit d'être humain(e). Vous n'avez pas à être fort(e) tout le temps.",
        "Votre valeur ne dépend pas de vos hauts et de vos bas émotionnels.",
        "Petit à petit, les nuages se disperseront. Gardez espoir.",
        "Même les cœurs lourds finissent par retrouver leur légèreté.",
        "Je vous envoie toute ma tendresse virtuelle. Vous n’êtes pas seul(e).",
        "Chaque larme est un pas vers la libération de votre âme.",
        "Vous êtes précieux(se), exactement tel(le) que vous êtes aujourd'hui.",
        "Vous avez déjà survécu à tant de choses. Vous traverserez aussi celle-ci.",
        "Je suis là pour vous, dans la tristesse comme dans la joie.",
        "Prenez votre temps, il n'y a pas de calendrier pour la guérison.",
    ],

    # Compliments spontanés
    "fais-moi un compliment spontané": [
        "Votre positivité est contagieuse ! ✨",
        "Vous êtes une belle source d'inspiration 💡",
        "Votre sourire illumine la journée de ceux qui vous entourent ! 😄",
        "J’admire votre capacité à voir le bon côté des choses.",
        "Vous avez une belle énergie qui donne envie d’avancer ! ⚡",
        "Votre gentillesse est un véritable rayon de soleil 🌞",
        "Vous dégagez une intelligence et une sensibilité rares.",
        "Votre détermination est une force incroyable.",
        "Vous êtes une personne sur qui on peut toujours compter 🤝",
        "Votre authenticité est votre plus grand atout.",
        "Vous avez une créativité débordante, c’est fascinant ! 🎨",
        "J’aime votre capacité à écouter et comprendre les autres.",
        "Votre esprit est aussi vif qu'inspirant. 🚀",
        "Vous rendez le monde meilleur simplement en étant vous-même.",
        "Votre enthousiasme est rafraîchissant, continuez ainsi !",
        "Vous êtes une belle âme, unique et précieuse 🌟",
        "Votre curiosité est une magnifique qualité.",
        "Votre générosité touche le cœur de ceux qui croisent votre chemin.",
        "Vous avez un regard unique qui enrichit tout ce que vous entreprenez.",
        "Votre calme et votre sérénité sont une véritable source d'apaisement.",
        "Votre sourire est une invitation à la bonne humeur ! 😁",
        "Vous avez une force intérieure admirable.",
        "Votre humour apporte de la légèreté partout où vous passez !",
        "Votre présence est toujours un cadeau pour ceux qui vous entourent 🎁",
        "Votre passion est communicative et incroyablement inspirante.",
        "Votre courage face aux défis est digne d'admiration.",
        "Vous êtes une personne lumineuse qui éclaire même les jours gris.",
        "Votre optimisme est un modèle à suivre.",
        "Votre sincérité est une rareté précieuse.",
        "Votre attention aux détails rend tout ce que vous faites spécial.",
        "Vous avez un cœur en or, ne doutez jamais de votre valeur. 💛",
        "Votre voix intérieure mérite d'être écoutée : elle est porteuse de sagesse.",
        "Vous êtes une étincelle de bonheur dans un monde parfois terne.",
        "Votre détermination inspire confiance et admiration.",
        "Votre capacité à rêver grand est impressionnante ! ✨",
        "Vous avez ce don rare de faire sourire même sans dire un mot.",
        "Votre aura positive est ressentie bien au-delà des mots.",
    ],

    # Petites phrases philosophiques
    "donne-moi une phrase philosophique": [
        "Le bonheur ne se cherche pas, il se remarque 🌸",
        "Chaque jour est un nouveau chapitre à écrire 📖",
        "C’est dans les épreuves que l’on découvre sa véritable force 💪",
        "Le véritable voyage n’est pas de chercher de nouveaux paysages, mais d’avoir de nouveaux yeux 🌍",
        "Ralentir, parfois, c'est avancer plus sûrement 🐢",
        "On ne peut pas arrêter les vagues, mais on peut apprendre à surfer 🌊",
        "La plus grande richesse est celle du cœur 💖",
        "Tout ce que vous cherchez à l'extérieur est déjà en vous 🌟",
        "Il n’y a pas de raccourci vers un endroit qui en vaut la peine 🛤️",
        "Même la nuit la plus sombre prendra fin, et le soleil se lèvera 🌅",
        "La vie est comme un écho : ce que vous envoyez revient vers vous 🔄",
        "N'attendez pas que le moment parfait arrive, créez-le ✨",
        "La simplicité est la sophistication suprême 🎨",
        "Quand on ne peut changer les choses, il faut changer son regard 👁️",
        "Être soi-même est la plus belle des libertés 🕊️",
        "Les petites graines d'aujourd'hui sont les grandes forêts de demain 🌳",
        "Le temps que vous perdez à douter pourrait être utilisé pour créer 🔥",
        "Les grandes choses prennent du temps, soyez patient 🌱",
        "On grandit non pas en évitant les tempêtes, mais en dansant sous la pluie ☔",
        "Chaque échec est un pas de plus vers la réussite 🚀",
        "La gratitude transforme ce que nous avons en suffisance 🙏",
        "Vous ne pouvez pas traverser la mer simplement en regardant l’eau 🌊",
        "La vie est courte, mais ses possibilités sont infinies ♾️",
        "Le vrai changement commence toujours à l’intérieur 💡",
        "Accepte ce qui est, laisse aller ce qui était, aie confiance en ce qui sera 🍃",
        "Les pensées d’aujourd'hui façonnent la réalité de demain 🧠",
        "Un esprit serein est un trésor inestimable 💎",
        "Ce ne sont pas les événements qui déterminent votre vie, mais votre manière de les vivre 🎭",
        "Celui qui déplace une montagne commence par déplacer de petites pierres 🏔️",
        "Le plus beau voyage est celui qu’on fait vers soi-même 🚶‍♂️",
        "Un cœur ouvert voit la beauté partout ❤️",
        "Ose être différent, c’est là que réside la magie ✨",
        "La lumière intérieure est plus forte que toutes les ombres extérieures 🔥",
        "Il n'y a pas de hasard, seulement des rendez-vous 📅",
        "Se perdre est parfois la meilleure manière de se trouver 🧭",
        "La paix intérieure commence lorsque vous choisissez de ne pas laisser les autres contrôler vos émotions 🌸",
    ],
    # Questions complexes avec réponses développées
    "comment trouver sa voie dans la vie": [
        "Trouver sa voie est un voyage personnel et unique. Commencez par explorer ce qui vous fait vibrer intérieurement, vos passions, vos valeurs profondes. Prenez le temps de tester différentes expériences sans peur de l'échec. Chaque pas, même incertain, vous rapproche de votre vérité intérieure. Soyez patient(e), votre voie se révélera à travers l'action, pas uniquement à travers la réflexion.",
        "La voie se découvre en chemin, rarement d’un seul coup. Autorisez-vous à écouter votre intuition, à suivre ce qui vous anime même si cela semble incertain. La persévérance, l'ouverture d’esprit et le courage d’essayer sont vos meilleurs alliés. Rappelez-vous : vous n'avez pas besoin d’avoir toutes les réponses pour avancer."
    ],

    "comment surmonter l'échec": [
        "L’échec n’est pas une fin, mais un enseignant puissant. Chaque revers vous offre une opportunité d’apprendre, de vous renforcer, et de mieux comprendre ce qui compte pour vous. Il est normal de ressentir de la déception, mais il est essentiel de ne pas laisser l’échec définir votre valeur. Relevez-vous, ajustez votre cap, et avancez avec une expérience enrichie.",
        "Acceptez l’échec comme une étape naturelle de toute croissance. Prenez du recul pour analyser les leçons cachées derrière chaque expérience difficile. Rappelez-vous : tomber fait partie du chemin, ce qui compte vraiment, c’est votre capacité à vous relever et à continuer à croire en vous."
    ],

    "comment garder la motivation sur le long terme": [
        "La motivation durable vient souvent d'un but profond et aligné avec vos valeurs. Fixez-vous des objectifs clairs, mais aussi donnez-vous des raisons émotionnelles de continuer. Célébrez chaque petit progrès, même invisible aux autres. Quand la motivation baisse, reconnectez-vous à votre 'pourquoi'. L’engagement l’emporte toujours sur la simple envie passagère.",
        "Ne comptez pas uniquement sur la motivation quotidienne : bâtissez une discipline douce et positive. Entourez-vous de rappels inspirants, variez vos approches pour garder la fraîcheur, et soyez indulgent(e) avec vous-même pendant les moments plus difficiles. La persévérance bienveillante est la clé."
    ],

    "comment mieux gérer ses émotions": [
        "Accueillir ses émotions sans jugement est la première étape. Observez-les comme des messagers, pas comme des ennemis. Prenez le temps de respirer profondément, d’identifier ce que vous ressentez et pourquoi. Exprimez vos émotions de manière saine, à l’écrit ou en dialogue. La gestion émotionnelle passe par l’acceptation, pas par la suppression.",
        "Chaque émotion est valable. L’important est d’apprendre à les traverser avec douceur plutôt que de les refouler. Pratiquer la respiration consciente, l’écriture libératrice ou simplement prendre un temps de pause peut profondément apaiser votre paysage intérieur."
    ],

    "comment devenir plus confiant(e)": [
        "La confiance est un muscle qui se développe avec l’action. Commencez par de petits engagements envers vous-même et tenez-les. Plus vous honorez vos propres promesses, plus vous bâtissez un socle de confiance intérieure. Cessez de vous comparer : vous êtes sur votre propre chemin.",
        "La confiance ne tombe pas du ciel, elle se cultive par la répétition et l'acceptation de ses imperfections. Chaque pas accompli avec courage, même minuscule, renforce votre fondation intérieure. Donnez-vous la permission d'être en chemin, et non obligé(e) d'être parfait(e)."
    ],

}
